# Remap control key
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like pane resizing
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

#
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind Space copy-mode

# Unbind
unbind C-u

# scrollback buffer n lines
set -g history-limit 100000

# Copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel
bind-key p paste-buffer

# on-screen time for display-panes in ms
set -g display-panes-time 5000

# Allow multiple commands to be entered without pressing the prefix-key again
set -g repeat-time 50

# start window indexing at one instead of zero
set -g base-index 0

#### statusbar ####
set -g status-interval 5
source "/usr/share/powerline/bindings/tmux/powerline.conf"
set -g status-position top

# default window title colors
set-window-option -g window-status-style fg=white,bg=default,dim

# active window title colors
set-window-option -g window-status-current-style fg=white
set-window-option -g window-status-current-style bg=default
set-window-option -g window-status-current-style bright

# Set escape-time
set-option -sg escape-time 10

# Set default terminal
set -g default-terminal "screen-256color"

# Clipboard
set -s set-clipboard external
